### ISSUE TITLE
Fix issues 

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/terriajs-dive#13]
According to @kring: TerriaJS is smart enough to route non-https requests via the proxy in order to avoid browser errorsthe only require is that the server be in the proxy whitelist(as an illustration, https://nationalmap.gov.au works fine even when connecting to maps on non-https servers

So @kring what exactly do we need to add  to the whitelist?
https://my.usgs.gov/bitbucket/projects/CDI/repos/terriamap/browse

https://maps-staging.snafu.cr.usgs.gov/TerriaMap/CDI-Dive/

**Comment by kring** [comment]
@rsignell-usgs you should add every host in your catalog to the proxy whitelist.
