### ISSUE TITLE
Install TerriaMap instance on a USGS site

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/terriajs-dive#5]
We have a TerriaMap fork at https://github.com/USGS-CMG/TerriaMap deployed currently at http://comt.sura.org/proxy_3001/ , which is an IOOS machine.    We should find a home for this at USGS.   We are hoping that maps.usgs.gov might be a suitable location.

**Comment by rsignell-usgs** [comment]
Following the procedures described in this Jira ticket:
https://my.usgs.gov/jira/servicedesk/customer/portal/2/OPS-4590
we now have a staging branch at
https://my.usgs.gov/bitbucket/projects/CDI/repos/terriajs-dive/browse?at=refs%2Fheads%2Fstaging
and a deployed instance at
https://maps-staging.snafu.cr.usgs.gov/TerriaMap/CDI-Dive/
(works only on USGS internal network currently, requiring VPN or TIC connection)

Eventually, Matt Davis (in Kevin Raney's group) will set this up to automatically deploy new commits, using Bamboo (Atlassian CI, similar to Github's Travis)

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , where do we stand on the generic endpoint for USGS work?

**Comment by zdefne-usgs** [comment]
@rsignell-usgs  Almost finished. Finally will test for installing the modified feedback tool within the Docker system.  If successful I will ping you so that you can update and test it on one of our servers too.

**Comment by zdefne-usgs** [comment]
It is ready to be tested on a USGS server now.  I created a PR, let me know if I missed anything. 
https://github.com/rsignell-usgs/docker-terria-usgs/pull/1

**Comment by rsignell-usgs** [comment]
TerriaMap is deployed at:   https://maps.usgs.gov/terriamap
